export const CONTROLLER_CONSTANTS = {
  NFT: 'nft',
  IMAGE: 'image',
  MOMENT: 'moment',
  COLLECTION: 'collection',
  AUTH: 'auth',
  LOG: 'log',
  PACK: 'pack',
  USER: 'user',
  KMS: 'kms',
};
export const URL_CONSTANTS = {
  RESUME_MINT_JOB: ':id/resume_mint',
  FINISH_MINT_JOB: ':id/finish_mint',
  GET_NFT_BY_ID: '',
  GET_OWNED_NFT: 'owned',
  GET_OWNED_PACK: 'owned',
  REDEEM_PACK: 'redeem',
  OPEN_PACK: 'open',
  // TRANSFER_NFT: ':id/transfer',
  CREATE_MOMENT: 'create_moment',
  CREATE_COLLECTION: 'create_collection',
  VIEW_COLLECTION: '',
  SIGN_IN: 'signin/creator',
  PUBLISH_COLLECTION: ':id/publish',
  CHECK_PUBLISH_COLLECTION: ':id/check_publish',
  UPDATE_COLLECTION: 'update',
  UPDATE_MOMENT: ':id/update',
  GET_MOMENT_BY_ID: '',
  GET_MOMENT_ONCHAIN: 'onchain',
  GET_COLLECTION_BY_ID: 'detail',
  GET_COLLECTION_ASSET: 'asset',
  CHECK_HAS_MINTING_MOMENT: 'check_mint',
  BLANK_COLLECTION: 'blank',
  GET_DEPOSIT_LOG: 'deposit',
  GET_CREATIVE_LOG: 'creative',
  GET_DEPLOY_CONTRACT_LOG: 'creative/:momentId/contract',
  GET_MINT_NFT_LOG: 'creative/:momentId/nft',
  REVEAL_COLLECTION: 'reveal',
  USER_SIGN_IN: 'signin/user',
  GET_ASSET_INFO: 'asset',
  USER_GET_COLLECTION_DETAIL: 'user/detail',
  GET_COLLECTION_FANSITE: 'fansite',
  CHECK_REVEAL_COLLECTION: 'check_reveal',
  NFT_BOARD: 'nft_board',
  USER_BOARD: 'user_board',
  CONCEAL_COLLECTION: 'conceal_collection',
  KEEP_COLLECTION: 'keep_collection',
  GET_SPECIAL_COLLECTION: 'head',
  AVAILABLE_REDEEM_COLLECTION: 'redeem_collection',
  INSTANTIATE_CONTRACT: 'instantiate_contract',
  MINT_NFT: 'mint_nft',
  TRANSFER_NFT: 'transfer_nft',
  CONNECT_KMS: ':id/connect',
  SIGN_BY_KMS: ':id/sign',
};
